services:
  uptime:
    image: louislam/uptime-kuma:2.0.0-beta.1@sha256:37cefd560df5c39222e34a487389fe3d38bd767ce6e3cf06da0b64e288f552c6
    restart: always
    user: 1000:1000
    environment:
      - UPTIME_KUMA_DB_TYPE=mariadb
      - UPTIME_KUMA_DB_HOSTNAME=${DB_HOSTNAME:?}
      - UPTIME_KUMA_DB_PORT=3306
      - UPTIME_KUMA_DB_NAME=${DB_NAME:?}
      - UPTIME_KUMA_DB_USERNAME=${DB_USERNAME:?}
      - UPTIME_KUMA_DB_PASSWORD=${DB_PASSWORD:?}
    networks:
      - default
      - reverse-proxy
    volumes:
      - uptime_data:/app/data # the path before the : can be changed
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pbs-uptime.rule=Host(`status.scout.ch`)"
      - "traefik.http.routers.pbs-uptime.entrypoints=https"
      - "traefik.http.services.pbs-uptime.loadbalancer.server.port=3001"
volumes:
  uptime_data:
networks:
  reverse-proxy:
    external: true
